### ISSUE TITLE
Unknown M code: M33 - Prusa MK3S

### ISSUE THREAD

**Issue by NightSkySK** [Petttkous/OctoPrint-Longpathsdlist#3]
![image](https://user-images.githubusercontent.com/52137446/107624724-92769200-6c5b-11eb-843b-655b2f5b389b.png)

OctoPrint 1.5.3 Python 3.7.3 OctoPi 0.18.0

Terminal shows the following message:
```
Send: M33 /holder~1.gco
Recv: Unknown M code: M33 /holder~1.gco
```
Printer Prusa i3 MK3S FW: 3.9.3

**Comment by mastahype** [comment]
Prusa firmware doesn't support the M33 command code or any of the other extended file commands from what I've read [here](https://www.reprap.org/wiki/G-code#M20:_List_SD_card) and [here](https://prusa3d.github.io/Prusa-Firmware-Doc/group__GCodes.html).
