### ISSUE TITLE
Don't understand your final advise

### ISSUE THREAD

**Issue by lluisd** [Petttkous/OctoPrint-Longpathsdlist#6]
You said "When too many files are present on the SD card the serial communication could be overflooded. This could result in the printer pausing while printing over USB for a few seconds at most. Use at your own risk!"

what does it mean? I only use the SD card to manually add the files to print and then octoprint to print directly from SD card. I don't use USB port for printing with an usb stick/pendrive, only the usb cable to connect my raspberry pi to my printer.

thank you!

**Comment by erstert3st** [comment]
He says while you are  printing via usb (gcode file is stored on pi)  and you refresh the files on the octoprint page or insert a new sd card in the printer than it could be overflooded but you need many files on the sdcard
